export type Event = {
  id: number;
  year: number;
  month: number;
  day: number;
  start: number;
  end: number;
  title: string;
  color: string;
  icon: string;
};

export const events: Event[] = [
  {
    id: 1,
    year: 2025,
    month: 1,
    day: 20,
    start: 15,
    end: 17,
    title: "Customer Research",
    color: "#f6daa7",
    icon: "ladder",
  },
  {
    id: 2,
    year: 2025,
    month: 1,
    day: 21,
    start: 14,
    end: 16,
    title: "Event Planning",
    color: "#f6daa7",
    icon: "ball",
  },
  {
    id: 3,
    year: 2025,
    month: 1,
    day: 22,
    start: 17,
    end: 18,
    title: "Public Relations",
    color: "#a2d5f2",
    icon: "ball",
  },
  {
    id: 4,
    year: 2025,
    month: 1,
    day: 23,
    start: 10,
    end: 11,
    title: "Investor Meeting",
    color: "#ffb6c1",
    icon: "ball",
  },
  {
    id: 5,
    year: 2025,
    month: 1,
    day: 23,
    start: 11,
    end: 13,
    title: "Public Relations",
    color: "#a2d5f2",
    icon: "music",
  },
  {
    id: 6,
    year: 2025,
    month: 1,
    day: 23,
    start: 14,
    end: 15,
    title: "UX/UI Workshop",
    color: "#a2d5f2",
    icon: "ball",
  },
  {
    id: 7,
    year: 2025,
    month: 1,
    day: 24,
    start: 13,
    end: 14,
    title: "Bug Fixing",
    color: "#a2d5f2",
    icon: "ladder",
  },
  {
    id: 8,
    year: 2025,
    month: 1,
    day: 25,
    start: 16,
    end: 17,
    title: "Legal Compliance",
    color: "#a2d5f2",
    icon: "ball",
  },
  {
    id: 9,
    year: 2025,
    month: 1,
    day: 25,
    start: 10,
    end: 12,
    title: "Sprint Meeting",
    color: "#a2d5f2",
    icon: "music",
  },
  {
    id: 10,
    year: 2025,
    month: 1,
    day: 25,
    start: 14,
    end: 16,
    title: "End-of-Month Recap",
    color: "#f6daa7",
    icon: "ball",
  },
  {
    id: 11,
    year: 2025,
    month: 1,
    day: 26,
    start: 17,
    end: 18,
    title: "Tech Talk",
    color: "#a2d5f2",
    icon: "ladder",
  },
  {
    id: 12,
    year: 2025,
    month: 1,
    day: 26,
    start: 10,
    end: 11,
    title: "Networking Event",
    color: "#f6daa7",
    icon: "music",
  },
  {
    id: 13,
    year: 2025,
    month: 1,
    day: 27,
    start: 14,
    end: 16,
    title: "Marketing Strategy",
    color: "#ffb6c1",
    icon: "music",
  },
  {
    id: 14,
    year: 2025,
    month: 1,
    day: 27,
    start: 10,
    end: 11,
    title: "UX/UI Workshop",
    color: "#a2d5f2",
    icon: "ladder",
  },
  {
    id: 15,
    year: 2025,
    month: 1,
    day: 27,
    start: 15,
    end: 16,
    title: "Product Launch",
    color: "#a2d5f2",
    icon: "ball",
  },
  {
    id: 16,
    year: 2025,
    month: 1,
    day: 28,
    start: 17,
    end: 18,
    title: "Code Review",
    color: "#ffb6c1",
    icon: "ball",
  },
  {
    id: 17,
    year: 2025,
    month: 1,
    day: 28,
    start: 9,
    end: 10,
    title: "Legal Compliance",
    color: "#ffb6c1",
    icon: "music",
  },
  {
    id: 18,
    year: 2025,
    month: 2,
    day: 1,
    start: 12,
    end: 13,
    title: "Sprint Meeting",
    color: "#ffb6c1",
    icon: "ball",
  },
  {
    id: 19,
    year: 2025,
    month: 2,
    day: 1,
    start: 15,
    end: 16,
    title: "Customer Research",
    color: "#ffb6c1",
    icon: "ladder",
  },
  {
    id: 20,
    year: 2025,
    month: 2,
    day: 1,
    start: 17,
    end: 18,
    title: "Code Review",
    color: "#ffb6c1",
    icon: "ladder",
  },
  {
    id: 21,
    year: 2025,
    month: 2,
    day: 2,
    start: 10,
    end: 11,
    title: "Development Sync",
    color: "#a2d5f2",
    icon: "ball",
  },
  {
    id: 22,
    year: 2025,
    month: 2,
    day: 2,
    start: 15,
    end: 17,
    title: "Sprint Meeting",
    color: "#f6daa7",
    icon: "ball",
  },
  {
    id: 23,
    year: 2025,
    month: 2,
    day: 2,
    start: 16,
    end: 17,
    title: "Product Launch",
    color: "#f6daa7",
    icon: "ladder",
  },
  {
    id: 24,
    year: 2025,
    month: 2,
    day: 3,
    start: 17,
    end: 18,
    title: "End-of-Month Recap",
    color: "#ffb6c1",
    icon: "music",
  },
  {
    id: 25,
    year: 2025,
    month: 2,
    day: 3,
    start: 16,
    end: 18,
    title: "Design Feedback",
    color: "#ffb6c1",
    icon: "music",
  },
  {
    id: 26,
    year: 2025,
    month: 2,
    day: 3,
    start: 15,
    end: 17,
    title: "Performance Review",
    color: "#f6daa7",
    icon: "ladder",
  },
  {
    id: 27,
    year: 2025,
    month: 2,
    day: 4,
    start: 13,
    end: 15,
    title: "Training Session",
    color: "#f6daa7",
    icon: "ball",
  },
  {
    id: 28,
    year: 2025,
    month: 2,
    day: 4,
    start: 15,
    end: 17,
    title: "Bug Fixing",
    color: "#ffb6c1",
    icon: "ladder",
  },
  {
    id: 29,
    year: 2025,
    month: 2,
    day: 4,
    start: 11,
    end: 12,
    title: "Customer Research",
    color: "#a2d5f2",
    icon: "ladder",
  },
  {
    id: 30,
    year: 2025,
    month: 2,
    day: 5,
    start: 15,
    end: 16,
    title: "Customer Research",
    color: "#f6daa7",
    icon: "ladder",
  },
  {
    id: 31,
    year: 2025,
    month: 2,
    day: 6,
    start: 12,
    end: 14,
    title: "End-of-Month Recap",
    color: "#ffb6c1",
    icon: "ball",
  },
  {
    id: 32,
    year: 2025,
    month: 2,
    day: 6,
    start: 11,
    end: 13,
    title: "Finance Review",
    color: "#ffb6c1",
    icon: "ladder",
  },
  {
    id: 33,
    year: 2025,
    month: 2,
    day: 6,
    start: 15,
    end: 17,
    title: "Public Relations",
    color: "#f6daa7",
    icon: "ball",
  },
  {
    id: 34,
    year: 2025,
    month: 2,
    day: 7,
    start: 16,
    end: 18,
    title: "Development Sync",
    color: "#a2d5f2",
    icon: "ball",
  },
  {
    id: 35,
    year: 2025,
    month: 2,
    day: 7,
    start: 9,
    end: 11,
    title: "Design Feedback",
    color: "#ffb6c1",
    icon: "ball",
  },
  {
    id: 36,
    year: 2025,
    month: 2,
    day: 8,
    start: 15,
    end: 17,
    title: "Legal Compliance",
    color: "#f6daa7",
    icon: "music",
  },
  {
    id: 37,
    year: 2025,
    month: 2,
    day: 8,
    start: 13,
    end: 14,
    title: "Cybersecurity Update",
    color: "#f6daa7",
    icon: "music",
  },
  {
    id: 38,
    year: 2025,
    month: 2,
    day: 9,
    start: 17,
    end: 19,
    title: "Feature Release",
    color: "#ffb6c1",
    icon: "ball",
  },
  {
    id: 39,
    year: 2025,
    month: 2,
    day: 9,
    start: 10,
    end: 11,
    title: "Networking Event",
    color: "#a2d5f2",
    icon: "ladder",
  },
  {
    id: 40,
    year: 2025,
    month: 2,
    day: 10,
    start: 9,
    end: 11,
    title: "UX/UI Workshop",
    color: "#f6daa7",
    icon: "ladder",
  },
  {
    id: 41,
    year: 2025,
    month: 2,
    day: 11,
    start: 15,
    end: 17,
    title: "Training Session",
    color: "#f6daa7",
    icon: "ladder",
  },
  {
    id: 42,
    year: 2025,
    month: 2,
    day: 12,
    start: 9,
    end: 10,
    title: "Project Planning",
    color: "#f6daa7",
    icon: "ball",
  },
  {
    id: 43,
    year: 2025,
    month: 2,
    day: 13,
    start: 16,
    end: 17,
    title: "Customer Research",
    color: "#a2d5f2",
    icon: "music",
  },
  {
    id: 44,
    year: 2025,
    month: 2,
    day: 13,
    start: 11,
    end: 12,
    title: "UX/UI Workshop",
    color: "#a2d5f2",
    icon: "ladder",
  },
  {
    id: 45,
    year: 2025,
    month: 2,
    day: 14,
    start: 16,
    end: 18,
    title: "Feature Release",
    color: "#f6daa7",
    icon: "ladder",
  },
  {
    id: 46,
    year: 2025,
    month: 2,
    day: 14,
    start: 11,
    end: 13,
    title: "Cybersecurity Update",
    color: "#ffb6c1",
    icon: "ladder",
  },
  {
    id: 47,
    year: 2025,
    month: 2,
    day: 14,
    start: 10,
    end: 11,
    title: "Event Planning",
    color: "#a2d5f2",
    icon: "ball",
  },
  {
    id: 48,
    year: 2025,
    month: 2,
    day: 15,
    start: 15,
    end: 17,
    title: "Feature Release",
    color: "#ffb6c1",
    icon: "ball",
  },
  {
    id: 49,
    year: 2025,
    month: 2,
    day: 15,
    start: 16,
    end: 18,
    title: "Product Launch",
    color: "#f6daa7",
    icon: "music",
  },
  {
    id: 50,
    year: 2025,
    month: 2,
    day: 15,
    start: 17,
    end: 19,
    title: "AI Research",
    color: "#a2d5f2",
    icon: "ball",
  },
  {
    id: 51,
    year: 2025,
    month: 2,
    day: 16,
    start: 12,
    end: 14,
    title: "Design Feedback",
    color: "#ffb6c1",
    icon: "ladder",
  },
  {
    id: 52,
    year: 2025,
    month: 2,
    day: 17,
    start: 14,
    end: 16,
    title: "Code Review",
    color: "#ffb6c1",
    icon: "ladder",
  },
  {
    id: 53,
    year: 2025,
    month: 2,
    day: 17,
    start: 15,
    end: 16,
    title: "Finance Review",
    color: "#a2d5f2",
    icon: "ball",
  },
  {
    id: 54,
    year: 2025,
    month: 2,
    day: 17,
    start: 11,
    end: 12,
    title: "Event Planning",
    color: "#f6daa7",
    icon: "ladder",
  },
  {
    id: 55,
    year: 2025,
    month: 2,
    day: 18,
    start: 16,
    end: 18,
    title: "Tech Talk",
    color: "#a2d5f2",
    icon: "ladder",
  },
  {
    id: 56,
    year: 2025,
    month: 2,
    day: 18,
    start: 15,
    end: 17,
    title: "Security Briefing",
    color: "#ffb6c1",
    icon: "music",
  },
  {
    id: 57,
    year: 2025,
    month: 2,
    day: 19,
    start: 12,
    end: 14,
    title: "Hiring Discussion",
    color: "#f6daa7",
    icon: "ball",
  },
  {
    id: 58,
    year: 2025,
    month: 2,
    day: 19,
    start: 16,
    end: 17,
    title: "Feature Release",
    color: "#f6daa7",
    icon: "ladder",
  },
  {
    id: 59,
    year: 2025,
    month: 2,
    day: 20,
    start: 13,
    end: 15,
    title: "Product Launch",
    color: "#f6daa7",
    icon: "ball",
  },
];
